gui:
  title: '宝可梦消消乐'
  hideItemM: STONE
  pokeItemN: '{pokemon_name}'

xxl-list:
  自定义1:
    - 'Ditto'
    - '小火龙'
    - '玛夏多'
    - '喷火龙'
    - '妙蛙花'
  自定义2:
    - 'MissingNo'
    - '小火龙'
    - '火恐龙'
    - '喷火龙'
    - '喷火龙'
    - '妙蛙花'
    - '妙蛙种子'
    - '妙蛙草'

  msg:
    play: '&a游戏开始了~'
    end: '&3游戏已结束&7|&3用时:&a{use_time}'
    abandon: '&c你放弃了这场游戏'