runCmd:
  ##默认范围的时候会用这个也就是直接使用begin指令不加后面的列表的那场游戏
  clearUp:
    - 'msg %player_name% 消除了一对宝可梦(分手大湿)'
  start:
    - 'say %player_name% 开始尝试消消乐'
  success:
    - 'minecraft:give %player_name% minecraft:diamond 1'
    - 'say %player_name% 恭喜玩家完成消消乐获得 钻石 一个'
  abandon:
    - 'say %player_name% 居然放弃了这么简单的消消乐'
listRunCmd:
  ##更具消消乐插件内配置的范围的列表名字来配置
  list1:
    clearUp:
      - 'msg %player_name% 消除了一对宝可梦(分手大湿)test'
    start:
      - 'say %player_name% 开始尝试消消乐test'
    success:
      - 'minecraft:give %player_name% minecraft:diamond 1'
      - 'say %player_name% 恭喜玩家完成消消乐获得 钻石 一个test'
    abandon:
      - 'say %player_name% 居然放弃了这么简单的消消乐test'